name: Check labels not applied

on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize
  issue_comment:
    types:
      - created

jobs:
  check-needs-triage-not-applied:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/build-test')
    steps:
      - name: Fail if needs-triage label applied
        if: ${{ contains(github.event.pull_request.labels.*.name, 'needs-triage')}}
        run: exit 1

