name: Label pull request

on:
  pull_request_target:
    types: 
      - opened
      - reopened
  issue_comment:
    types:
      - created

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && containd(github.event.comment.body, '/build-test')}}
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
