name: Require semantic labels

on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize
  issue_comment:
    types:
      - created

jobs:
  check-pr-label-and-comment:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/build-test')
    steps:
      - uses: yashhy/pr-label-check-and-comment-action@v1.0.1
        with:
          # This list is duplicated from release-drafter.yml
          required_labels: 'chore,ci,cleanup,docs,feat,fix,perf,refactor,style,test'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
