name: semantic-pull-request

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize
  issue_comment:
    types:
      - created


jobs:
  main:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/build-test')
    steps:
      - uses: amannn/action-semantic-pull-request@v3.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
